# Generated by Django 5.2 on 2025-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='loja',
            field=models.CharField(default='Loja Padrão', max_length=100),
        ),
    ]
