# Generated by Django 5.2 on 2025-05-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_carrinho_cliente_remove_carrinho_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
    ]
