# Generated by Django 5.2 on 2025-06-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_itempedido_produto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
