# Generated by Django 5.2 on 2025-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Pix', 'Pix'), ('Dinheiro', 'Dinheiro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
