# Generated by Django 5.2 on 2025-06-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_pedido_produto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregador',
            new_name='Entregadores',
        ),
    ]
