# Generated by Django 5.2 on 2025-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_entregador_entregadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_servico',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa de serviço do Ilha Delivery.', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_produto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor original do produto/serviço (sem a taxa).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final a ser pago pelo cliente (produto + taxa).', max_digits=10, null=True),
        ),
    ]
