site_name: Projeto Ilha Delivery
docs_dir: docs
site_description: Documentação do projeto Ilha Delivery
repo_url: https://github.com/Projetos-de-Extensao/2025.1_01_IlhaDelivery

theme:
  name: material
  palette:
    primary: default
  color_mode: dark
  language: pt-BR
  favicon: images/favicon.png
  user_color_mode_toggle: true
  logo: assets/ibmec_logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select
    - content.code.annotate 

plugins:
  - search

extra:
  consent:
    actions:
      - accept
      - manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

