@startsalt Sobre
{

{T
  | **ILHA DELIVERY**         | [Início] [Pedidos] [Sobre] [Perfil] |
}

{T
  | <color:red><size:20>**SOBRE NÓS**</size></color> |
  | Bem-vindo ao <b><color:red>Ilha Delivery</color></b>!\n
    Nossa missão é conectar você aos melhores serviços e produtos da região,\n
    garantindo rapidez, qualidade e praticidade. |
}

{+
  {T
    | 🚀 <b>Missão</b> |
    | Entregar qualidade e\nagilidade a cada cliente. |
  }
  {T
    | 🌍 <b>Visão</b> |
    | Ser a plataforma referência\nem delivery na ilha. |
  }
  {T
    | 💡 <b>Valores</b> |
    | Compromisso, inovação\ne excelência. |
  }
}
}
@endsalt
