@startsalt Login

{
{T
  | **ILHA DELIVERY**         | [Início] [Pedidos] [Sobre] [Perfil] |
}

{+
  <&person> **Login**     | ["Digite seu e-mail"]
  <&key> **Senha**        | ["********"]

  <&entrar> |[Entrar]


  <&google> | [Entrar com Google]
}
}

@endsalt
